<?php
ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(E_ALL);
ob_start();
include('conection.php');
$id_session=$_GET['id'];
$info=mysqli_query($link,"SELECT*FROM`film_session`WHERE`id`='$id_session'");
$info2=mysqli_fetch_assoc($info);
$aDoor=$_POST['formDoor'];
if(empty($aDoor)){
header('Location:/');
}
else
{
$N=count($aDoor);
if($_COOKIE['user']!=''){
$placesline=unserialize($info2['places']);
for($i=0;$i<$N;$i++)
{
$film=$info2['name'];
$user=$_COOKIE['user'];
$price=$info2['cost'];
$place=$aDoor[$i]-1;
$infohall=$info2['hall'];
$result=mysqli_query($link,"INSERT INTO`tickets`(`user`,`price`,`hall`,`place`,`film`)
VALUES('$user','$price','$infohall','$place','$film')");
$placesline[$place]=1;
}
$serializeres=serialize($placesline);
$resultchange=mysqli_query($link,"UPDATE `film_session` SET `places`='$serializeres'WHERE`id`='$id_session'");
ob_start();
header('Location:Cabinet.php');
ob_enf_fluch();
}
else{
ob_start();
header('Location:registr.php');
ob_enf_fluch();
}
}
?>
